#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# npm run lint
# npm run format
npx lint-staged

#  "lint-staged": {
#     "*.{js,jsx,ts,tsx}": ["eslint"],
#     "*":["prettier --write --ignore-unknown"]
#   },