#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# npm run lint && npm run format
# npm run format
# npm run precommit
npm run lint-staged

#  "lint-staged": {
#     "*.{js,jsx,ts,tsx}": ["eslint"],
#     "*":["prettier --write --ignore-unknown"]
#   },